### ISSUE TITLE
Ok, how to up and run titan via docker-compose for production?

### ISSUE THREAD

**Issue by biow0lf** [oxisto/titan#90]
I try this `docker-compose.yml` file:

```
docker-compose.yml 
version: "3.7"

volumes:
  redis_data: {}
  postresql_data: {}

services:
  redis:
    image: "redis:5.0.7"
    container_name: "titan_redis"
    restart: "unless-stopped"
    volumes:
      - "redis_data:/data"

  postgresql:
    image: "postgres:12.1"
    container_name: "titan_postgresql"
    restart: "unless-stopped"
    environment:
      POSTGRES_DB: titan
    volumes:
      - "postresql_data:/var/lib/postgresql/data"
      - "./postgres:/docker-entrypoint-initdb.d"

  titan:
    image: "oxisto/titan:latest"
    container_name: "titan_titan"
    restart: "unless-stopped"
    ports:
      - "4300:4300"
```

And it fail with:
```
titan_titan   | psql: error: could not connect to server: could not connect to server: Connection refused
titan_titan   | 	Is the server running on host "titan" (172.19.0.2) and accepting
titan_titan   | 	TCP/IP connections on port 5432?
titan_titan   | pg_restore: error: too many command-line arguments (first is "sde-20190529-TRANQUILITY")
titan_titan   | Try "pg_restore --help" for more information.
titan_titan   | psql: error: could not connect to server: could not connect to server: Connection refused
titan_titan   | 	Is the server running on host "titan" (172.19.0.2) and accepting
titan_titan   | 	TCP/IP connections on port 5432?
titan_titan   | time="2020-02-13T20:04:20Z" level=error msg="Could not read config: Config File \"config\" Not Found in \"[/usr/titan/config]\""
titan_titan   | time="2020-02-13T20:04:20Z" level=info msg="Starting server..."
titan_titan   | time="2020-02-13T20:04:20Z" level=error msg="Could not initialize EVE SSO, please specify a client ID, secret and redirect URI."
titan_titan exited with code 0
```

So, what should be in config? And what is config format?

**Comment by biow0lf** [comment]
Ping?

**Comment by oxisto** [comment]
Hi sorry for the delayed response. I have updated the https://github.com/oxisto/titan/blob/master/README.md to reflect an example config. Basically, I am using cobra/viper, so you have three different options of configuring (all possible with docker-compose) the config values defined here:
 https://github.com/oxisto/titan/blob/3839a8e4b86ae48c5d4e0ee08c06e14c961c8aed/cmd/server/server.go#L46-L66

- Environmental variables. The prefix is `TITAN`, so the config option for the redis server becomes `TITAN_REDIS`
- Command line arguments, such as `--redis`
- A configuration file, stored in `config/config.yaml`

Because of legacy reasons, if you use the Docker image it is best to also specify `TITAN_POSTGRES` as environment variable, because the SDE import script will look for that variable and otherwise it will not populate DB, leading to the error that you saw.

So basically this self-contained `docker-compose.yml` should work (provided that you have registered your application in the EVE developer portal). Make sure to replace <clientID> and <secretKey>.

```
version: "3.7"

volumes:
  redis_data: {}
  postresql_data: {}

services:
  redis:
    image: redis:5
    container_name: "titan_redis"
    restart: "unless-stopped"
    volumes:
      - "redis_data:/data"

  postgres:
    image: postgres:12
    container_name: "titan_postgres"
    restart: "unless-stopped"
    environment:
      POSTGRES_DB: titan
    volumes:
      - "postresql_data:/var/lib/postgresql/data"
      - "./postgres:/docker-entrypoint-initdb.d"

  titan:
    image: "oxisto/titan:latest"
    container_name: "titan_titan"
    restart: "unless-stopped"
    environment:
      TITAN_POSTGRES: postgres
      TITAN_REDIS: redis:6379
      TITAN_EVE_CLIENTID: <clientID>
      TITAN_EVE_SECRETKEY: <secretKey>
      TITAN_EVE_REDIRECTURI: http://localhost:4300/auth/callback
    ports:
      - "4300:4300"
```

Please be aware, that it seems that currently the dashboard is broken in the Docker containers (see #96). I am working on it
